export const data = [
    {   id: 1,
        arriveOrDeparture : 'arriving',
        time : '01:15',
        city : 'Rostov-on-Don',
        terminal: 'D',
        status : 'landed',
        flightNumber : 'SU 1169'
    },
    {       id: 2,
        arriveOrDeparture : 'departing',
        time : '02:21',
        city : 'Glasgow',
        terminal: 'B',
        status : 'landed',
        flightNumber : 'MLT 751'
    },
    {       id: 3,
        arriveOrDeparture : 'arriving',
        time : '03:05',
        city : 'Tel-Aviv',
        terminal: 'B',
        status : 'landed',
        flightNumber : 'SU 509'
    },
    {       id: 4,
        arriveOrDeparture : 'departing',
        time : '04:07',
        city : 'Miami',
        terminal: 'A',
        status : 'canceled',
        flightNumber : 'SU 112'
    },
    {       id: 5,
        arriveOrDeparture : 'arriving',
        time : '05:17',
        city : 'London',
        terminal: 'B',
        status : 'delayed',
        flightNumber : 'SU 2583'
    },
    {       id: 6,
        arriveOrDeparture : 'departing',
        time : '06:49',
        city : 'Ufa',
        terminal: 'D',
        status : 'delayed',
        flightNumber : 'SU 1234'
    },
    {   id: 7,
        arriveOrDeparture : 'arriving',
        time : '07:15',
        city : 'St.Petersburg',
        terminal: 'D',
        status : 'landed',
        flightNumber : 'SU 031'
    },
    {       id: 8,
        arriveOrDeparture : 'departing',
        time : '08:21',
        city : 'Amsterdam',
        terminal: 'B',
        status : 'expected at time',
        flightNumber : 'SU 3200'
    },
    {       id: 9,
        arriveOrDeparture : 'arriving',
        time : '09:05',
        city : 'Paris',
        terminal: 'A',
        status : 'landed',
        flightNumber : 'SU 3003'
    },
    {       id: 10,
        arriveOrDeparture : 'departing',
        time : '10:07',
        city : 'Surgut',
        terminal: 'D',
        status : 'canceled',
        flightNumber : 'SU 1512'
    },
    {       id: 11,
        arriveOrDeparture : 'arriving',
        time : '12:15',
        city : 'Amsterdam',
        terminal: 'B',
        status : 'delayed',
        flightNumber : 'SU 3203'
    },
    {       id: 12,
        arriveOrDeparture : 'departing',
        time : '14:19',
        city : 'Rome',
        terminal: 'B',
        status : 'delayed',
        flightNumber : 'AZ 595'
    },
    {   id: 13,
        arriveOrDeparture : 'arriving',
        time : '15:39',
        city : 'Riga',
        terminal: 'B',
        status : 'landed',
        flightNumber : 'SU 3975'
    },
    {       id: 14,
        arriveOrDeparture : 'departing',
        time : '16:21',
        city : 'Tomsk',
        terminal: 'D',
        status : 'expected at time',
        flightNumber : 'SU 1536'
    },
    {       id: 15,
        arriveOrDeparture : 'arriving',
        time : '18:52',
        city : 'Helsinki',
        terminal: 'A',
        status : 'landed',
        flightNumber : 'SU 3965'
    },
    {       id: 16,
        arriveOrDeparture : 'departing',
        time : '19:08',
        city : 'New York',
        terminal: 'A',
        status : 'canceled',
        flightNumber : 'SU 100'
    },
    {       id: 17,
        arriveOrDeparture : 'arriving',
        time : '21:23',
        city : 'Hamburg',
        terminal: 'B',
        status : 'delayed',
        flightNumber : 'SU 2349'
    },
    {       id: 18,
        arriveOrDeparture : 'departing',
        time : '22:39',
        city : 'Samara',
        terminal: 'D',
        status : 'delayed',
        flightNumber : 'SU 1206'
    }
];